#!/usr/bin/env python3

import curses
import sys
from hokm.client import HokmClient

def main(stdscr):
    argc = len(sys.argv)
    ip_addr = sys.argv[1] if argc > 1 else 'localhost'
    player_id = int(sys.argv[2]) if argc > 2 else 1
    client = HokmClient(stdscr, ip_addr, player_id)
    client.main()


if __name__ == '__main__':
    curses.wrapper(main)